services:
  # === BASE DE DATOS MYSQL ===
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expressnow_db
    ports:
      - "3306:3306"
    networks:
      - expressnow-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pgetrootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # === MICROSERVICIO 1: USUARIOS Y AUTENTICACIÓN ===
  usuarios-service:
    image: felipeduran33/expressnow-usuarios:latest
    container_name: usuarios-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/expressnow_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - JWT_SECRET=EstaEsUnaClaveSuperSecretaParaExpressNow2024
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - expressnow-network

  # === MICROSERVICIO 2: PRODUCTOS ===
  productos-service:
   image: felipeduran33/expressnow-productos:latest
   container_name: productos-service
   ports:
   - "8082:8082"
   environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/expressnow_productos_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
     - SPRING_DATASOURCE_USERNAME=root
     - SPRING_DATASOURCE_PASSWORD=rootpassword
     - JWT_SECRET=EstaEsUnaClaveSuperSecretaParaExpressNow2024
     - AWS_REGION=us-east-1
     - SQS_QUEUE_NAME=expressnow-alertas-stock-cola
     - AWS_ACCESS_KEY_ID=ASIARL53Y47RDMILAEN4
     - AWS_SECRET_ACCESS_KEY=rIvAMKSzjBtsVz7/vUWHY3AXOY2M7gLHvgk5XHm0
     - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEKD//////////wEaCXVzLXdlc3QtMiJIMEYCIQDg0KqkEzTIg8sF4BwnDo1EqLYWVsG3shQPoc5sDfGYwQIhAJuiCNlS2AgxDwmZ+7TRE1VzLyXco9kYRnq2GyHT1L3RKrACCGkQABoMMDk0MzQ2MjA5MjUwIgyFm6H7WnGDXEntnyMqjQIRkCCUglQQtuBlNiFRxY0sKrpWD/stf7JmE0U9lX0xDNGtwPv7DMCtfsk6HpMBSOM+1wqgtDr2QLkyAw/eN+H6entn3/pBbgYp4IOhnFaJvurCVpDax6AHuJgLBSm+oEgb2zmJMJ2irm+YAoxA4mFqf8RPUJ//kO4JL44IRXdO39HY8L2cVIE1OaLENRF6wN8ksUi1LS8KreIMdH6FlyaRosqWeV2j9v21wgaCv6a8zQi2ICO6g84ZHFvViY5cuY6p6ZmPYrIgkzs0MwVLuODPRrS984Xxi43iNu6B7TqKQvrhVb9V4sXYvINWwkuirs2w9oeSCWEkFXEohNvSKolhTGnTWxxjOXe5xOqsbzDV+erSBjqcAUjwy83/RAsceRj3hCKL/q45Rv4v4WfCyLyjqMEApTPb8TNZkgapFW1/ajUGNCABJHLeA77kw3ekx2yHgdOCIk5RAci6eFyA/WdvdxSnuBX693JviY4TeW9/9SnCufnwgb7TMSGBlvfTKfyQgr0cUTshDLb+z2XJ7FhXgWQfSxlognm4nxLt6cv2i95U/6idwR9C8yrgzaY6KdIehw==
   depends_on:
    mysql-db:
      condition: service_healthy
   networks:
    - expressnow-network

  # === MICROSERVICIO 3: CARRITO ===
  carrito-service:
    image: felipeduran33/expressnow-carrito:latest
    container_name: carrito-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/expressnow_carrito_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - JWT_SECRET=EstaEsUnaClaveSuperSecretaParaExpressNow2024

      # ---- CONFIGURACIÓN DE REGIÓN (N. VIRGINIA) ----
      - AWS_REGION=us-east-1

      # ---- VARIABLES DE LA COLA SQS EN US-EAST-1 ----
      - SQS_QUEUE_NAME=expressnow-alertas-stock-cola
      - AWS_SQS_QUEUE_NAME=expressnow-alertas-stock-cola
      - AWS_SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/094346209250/expressnow-alertas-stock-cola
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/094346209250/expressnow-alertas-stock-cola
      - SQS_URL=https://sqs.us-east-1.amazonaws.com/094346209250/expressnow-alertas-stock-cola

      # ---- CREDENCIALES DE AWS ACADEMY INTEGRADAS ----
      - AWS_ACCESS_KEY_ID=ASIARL53Y47RDMILAEN4
      - AWS_SECRET_ACCESS_KEY=rIvAMKSzjBtsVz7/vUWHY3AXOY2M7gLHvgk5XHm0
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEKD//////////wEaCXVzLXdlc3QtMiJIMEYCIQDg0KqkEzTIg8sF4BwnDo1EqLYWVsG3shQPoc5sDfGYwQIhAJuiCNlS2AgxDwmZ+7TRE1VzLyXco9kYRnq2GyHT1L3RKrACCGkQABoMMDk0MzQ2MjA5MjUwIgyFm6H7WnGDXEntnyMqjQIRkCCUglQQtuBlNiFRxY0sKrpWD/stf7JmE0U9lX0xDNGtwPv7DMCtfsk6HpMBSOM+1wqgtDr2QLkyAw/eN+H6entn3/pBbgYp4IOhnFaJvurCVpDax6AHuJgLBSm+oEgb2zmJMJ2irm+YAoxA4mFqf8RPUJ//kO4JL44IRXdO39HY8L2cVIE1OaLENRF6wN8ksUi1LS8KreIMdH6FlyaRosqWeV2j9v21wgaCv6a8zQi2ICO6g84ZHFvViY5cuY6p6ZmPYrIgkzs0MwVLuODPRrS984Xxi43iNu6B7TqKQvrhVb9V4sXYvINWwkuirs2w9oeSCWEkFXEohNvSKolhTGnTWxxjOXe5xOqsbzDV+erSBjqcAUjwy83/RAsceRj3hCKL/q45Rv4v4WfCyLyjqMEApTPb8TNZkgapFW1/ajUGNCABJHLeA77kw3ekx2yHgdOCIk5RAci6eFyA/WdvdxSnuBX693JviY4TeW9/9SnCufnwgb7TMSGBlvfTKfyQgr0cUTshDLb+z2XJ7FhXgWQfSxlognm4nxLt6cv2i95U/6idwR9C8yrgzaY6KdIehw==
      - USUARIOS_SERVICE_URL=http://usuarios-service:8081
      - PRODUCTOS_SERVICE_URL=http://productos-service:8082
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - expressnow-network

networks:
  expressnow-network:
    driver: bridge

volumes:
  mysql-data: